---
version: 2
plan:
  project-key: DEV
  key: JAVA
  name: spring-petclinic
  description: Plan de build creado con build specs yaml.
stages:
  - Build :
      - Build

Build:
  tasks:
    - clean
    - script:
        - echo '*******compile**********'
        - mvn compile -Dcheckstyle.skip
    - script:
        - echo '*******test**********'
        - mvn test -Dcheckstyle.skip
    - script:
        - echo '*******package**********'
        - mvn package -Dcheckstyle.skip
  final-tasks:
   - test-parser:
       type: junit
       test-results:
         - target/surefire-reports/*.xml
