---
version: 2
plan:
  project-key: DEV
  key: JAVA
  name: spring-petclinic
  description: Plan de build creado con build specs yaml.
stages:
  - Build :
      - Build

Build:
  tasks:
    - clean
    - script:
        - echo '*******compile**********'
        - mvn compile
    - script:
        - echo '*******test**********'
        - mvn test
    - script:
        - echo '*******package**********'
        - mvn package
 final-tasks:
    - test-parser:
        type: junit
        test-results:
          - **/target/surefire-reports/*.xml
          - target/test/xml-reports 
